services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_net

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 10 --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - redis_net

  transaction-checker:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGODB_URL=mongodb://mongo:27017/transactions
      - AMQP_SERVER_URI=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=transactions
      - SOCKET_ORIGIN_URL=http://localhost:3000
    volumes:
      - ./transaction-checker:/home/node/app
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - rabbitmq_net
      - mongo_net
      - socket_net

  transaction-generator:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    environment:
      - AMQP_SERVER_URI=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=transactions
    volumes:
      - ./transaction-generator:/home/node/app
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  transaction-api:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./transaction-api:/home/node/app
    depends_on:
      - mongo
      - redis
    networks:
      - mongo_net
      - redis_net
      - api_net

  transaction-logger:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./transaction-logger:/home/node/app
    networks:
      - api_net
      - socket_net
    depends_on:
      - transaction-checker

volumes:
    rabbitmq_data:
    rabbitmq_log:
    mongodb_data:
    redis:

networks:
  rabbitmq_net:
    driver: bridge

  mongo_net:
    driver: bridge
  
  redis_net:
    driver: bridge
  
  api_net:
    driver: bridge
  
  socket_net:
    driver: bridge
